//! Synthetic fixture builder. Round-trips a generated swap stream
//! through the engine, captures the engine's outputs, and packages them
//! as `LpPositionFixture` rows so the validation harness has data to
//! exercise without a live Alchemy key.
//!
//! This is the test-time surrogate for the M2.4 plan's "5 known on-chain
//! LP positions". The synthetic fixtures verify the harness mechanics;
//! the live fixtures (when keys are supplied) validate the engine
//! against on-chain ground truth.

use std::sync::Arc;

use num_bigint::BigUint;

use crate::backtest::{Engine, PositionConfig, RebalanceRule};
use crate::ingest::{decoder::SWAP_TOPIC0, EthLog, Ingester, MockArchiveSource};
use crate::math::tick_to_sqrt_price_x96;
use crate::storage::Storage;

use super::error::ValidationError;
use super::LpPositionFixture;

/// Number of synthetic fixtures generated by `round_trip_synthetic_fixtures`.
pub const SYNTHETIC_FIXTURE_COUNT: usize = 5;

/// Builds five synthetic LP-position fixtures with the engine output
/// recorded as the "on-chain ground truth". By construction every
/// fixture passes the validation harness — this exercises the harness
/// mechanics, not the engine's correctness against a real chain.
pub async fn round_trip_synthetic_fixtures(
    storage: &Storage,
) -> Result<Vec<LpPositionFixture>, ValidationError> {
    seed_pool_swaps(storage, "0xpool", 1000, 2000).await;
    let engine = Engine::new(storage);

    let configs = vec![
        ("centred-tight", -100, 100, 1500u64),
        ("centred-wide", -500, 500, 1500u64),
        ("upper-half", 0, 200, 1500u64),
        ("lower-half", -200, 0, 1500u64),
        ("very-wide", -1000, 1000, 1500u64),
    ];
    let mut fixtures = Vec::with_capacity(configs.len());
    for (label, tl, tu, exit_block) in configs {
        let config = PositionConfig {
            pool_address: "0xpool".into(),
            tick_lower: tl,
            tick_upper: tu,
            deposit_token0: "1000000000000000000".into(),
            deposit_token1: "3000000000".into(),
            entry_block: 1000,
            exit_block,
            fee_tier_bps: 5,
            token0_decimals: 18,
            token1_decimals: 6,
            mev_haircut_bps: 0.0,
        };
        let out = engine.simulate(config.clone(), RebalanceRule::Static).await?;
        fixtures.push(LpPositionFixture {
            label: label.to_string(),
            config,
            on_chain_fees_usd: out.summary.total_fees_usd,
            on_chain_mgmt_gas_usd: out.summary.total_mgmt_gas_usd,
            on_chain_final_value_usd: out.summary.final_value_usd,
        });
    }
    Ok(fixtures)
}

async fn seed_pool_swaps(storage: &Storage, pool: &str, from: u64, to: u64) {
    let mock = Arc::new(MockArchiveSource::new(to + 100));
    for b in from..=to {
        let tick = ((b - from) as i32 % 400) - 200;
        let sqrt = tick_to_sqrt_price_x96(tick).unwrap();
        let log = make_swap_log(pool, b, 0, &sqrt, 1_000_000_000_000u128, tick);
        mock.add_log(log);
        mock.set_block_gas(b, 20.0);
    }
    let ingester = Ingester::new(storage.clone(), mock);
    ingester.backfill(pool, from, to).await.unwrap();
}

fn make_swap_log(
    pool: &str,
    block: u64,
    log_idx: u64,
    sqrt: &BigUint,
    liquidity: u128,
    tick: i32,
) -> EthLog {
    let topic0 = format!("0x{SWAP_TOPIC0}");
    let topic1 = format!("0x{:0>64}", "1");
    let topic2 = format!("0x{:0>64}", "2");
    let a0 = encode_int256_word(1_000_000_000_000_000_000);
    let a1 = encode_int256_word(-3_000_000_000);
    let sq = format!("{:0>64}", sqrt.to_str_radix(16));
    let li = format!("{:0>64x}", liquidity);
    let tk = encode_int24_word(tick);
    EthLog {
        address: pool.to_string(),
        block_number: block,
        log_index: log_idx,
        transaction_hash: format!("0x{:0>64}", "deadbeef"),
        block_timestamp: 1_700_000_000 + (block as i64) * 12,
        topics: vec![topic0, topic1, topic2],
        data: format!("0x{a0}{a1}{sq}{li}{tk}"),
    }
}

fn encode_int24_word(value: i32) -> String {
    let raw = (value as u32) & 0x00FF_FFFF;
    if value < 0 {
        format!("{:0>58}{:06x}", "f".repeat(58), raw)
    } else {
        format!("{:0>64x}", raw)
    }
}

fn encode_int256_word(value: i64) -> String {
    if value >= 0 {
        format!("{:0>64x}", value as u64)
    } else {
        let two_to_256: BigUint = BigUint::from(1u8) << 256;
        let big: BigUint = two_to_256 - BigUint::from((-value) as u64);
        format!("{:0>64}", big.to_str_radix(16))
    }
}
